### ISSUE TITLE
400: Bad Request

### ISSUE THREAD

**Issue by mrpatrickstarkovich** [AlexxIT/Dataplicity#1]
После обновления core-2021.7.1

**Comment by Gferretta** [comment]
Idem error and version

No connect.

**Comment by mrpatrickstarkovich** [comment]
Вот здесь задают подобный вопрос
https://community.home-assistant.io/t/reverse-proxy-error/312936

Я добавил это в  configuration.yaml и все стало ok

http:
  server_port: 8123
  base_url: https://<URL_dataplicity>
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

**Comment by mrpatrickstarkovich** [comment]
Две недели назад в течении двух дней выходила ошибка 502. Но потом все заработало.

**Comment by Gferretta** [comment]
> Вот здесь задают подобный вопрос
> https://community.home-assistant.io/t/reverse-proxy-error/312936
> 
> Я добавил это в  configuration.yaml и все стало ok
> 
> http:
>   server_port: 8123
>   base_url: https://<URL_dataplicity>
>   use_x_forwarded_for: true
>   trusted_proxies:
>     - 127.0.0.1
>  

With this changes, local access with http://homeassistant.local:8123  work?

I'm only installed dataplicity for remote access and locally no https

Thanks

**Comment by Gferretta** [comment]
SOLVED!


Dataplicity working again.


**http:
  use_x_forwarded_for: true
  trusted_proxies:
     - 127.0.0.1**

**Comment by AlexxIT** [comment]
This is right solution. But I added these settings automatically to the component v1.0.4
