### ISSUE TITLE
unable to associate m2m identity

### ISSUE THREAD

**Issue by akonstster** [AlexxIT/Dataplicity#10]
Home Assistant 2021.12.9

Версия | core-2021.12.9

Тип установки | Home Assistant on OpenWrt
Среда разработки | false
Supervisor | false
Docker | false
Пользователь | root
Виртуальное окружение | false
Версия Python | 3.9.9
Семейство операционных систем | Linux
Версия операционной системы | 5.4.154
Архитектура ЦП | armv7l

Logger: agent
Source: deps/lib/python3.9/site-packages/dataplicity/client.py:308
First occurred: 15:51:45 (2 occurrences)
Last logged: 15:51:51

unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. put m2m/devices/6def9172-7311-4c85-9982-0b58a8997be3/ <Response [500]>")

**Comment by AlexxIT** [comment]
Some internal problems in Dataplicity service
