### ISSUE TITLE
Проблемы подключение к dataplicity

### ISSUE THREAD

**Issue by dangerdanik** [AlexxIT/Dataplicity#12]
Доброго времени! Опять проблема подключения к dataplicity. На сайте устройство мигает, затем зеленое. Но зайти в консоль не получается, ошибка - *** connection closed ***, ссылка на HA конечно не работает - Server Unavailable
The Dataplicity server is unavailable. Please try again later . Судя по всему проблема плавающая. Не могу понять это у меня или нет. Написал в dataplicity. Они ответили - Sorry about these issues . We'll be investigating them as soon as possible . I haven't gotten any reports today with regards to this issue and all my test devices are running fine too . Any chance you could check the logs on your device to see if it's something more local ? The logs can be found at /var/log/dataplicity.log . Подскажите где найти лог? Или может есть решение о котором мне не известно. Заранее спасибо!

**Comment by Vitls21** [comment]
Аналогичная проблема. Началось вчера кажется (может после обновления home assistant).
Если несколько раз нажимать retry при соединении, иногда подключается, но где-то не стабильно.

**Comment by dangerdanik** [comment]
До обновления HA у меня уже была эта проблема. Вчера вечером само стало работать. Обрадовался, думал может я что то все же накосячил. Сегодня утром 20.01.2022 опять не работает. Вот и не понятно(

**Comment by dangerdanik** [comment]
Кто то что то подкручивает. Сейчас опять работает 20.01.2022 13:10. Мониторинг что ли какой то прикручивать...

**Comment by Ucsus** [comment]
Обновился с утра на 2023.2.3, ща вообще не понимаю что происходит с dataplicity - сначала не пускал, переустановил интеграцию и новый wormhole, он меня редиректит то на графану, то basic-авторизация бесконечно вылезает, то еще на какие-то интерфейсы непонятные. В панели показывает Disk space: 768MB of 2GB used, хотя у меня там 120 гигов. ХА ругается "Login attempt or request with invalid authentication from 5-255-199-19.nat64.yandex.net (5.255.199.19). "

**Comment by dangerdanik** [comment]
У меня та же проблема. Давно не было. И вот появилось(. Год наверное нормально все было.

**Comment by alexanderznamensky** [comment]
+1

**Comment by Gferretta** [comment]
+1

And since the DATAPLICITY cut, attempts to log in from any direction in the world began to appear, something that had not happened before.
hacked?

**Comment by BBrylov** [comment]
точно такая же проблема

**Comment by DenisYeremchenko** [comment]
Точно такая же проблема всплыла, решения пока никто не нашел?
