### ISSUE TITLE
Очень долгая загрузка интеграции

### ISSUE THREAD

**Issue by M0DDer** [AlexxIT/Dataplicity#14]
Уже несколько десятков обновлений НА имею проблемы с ингергацией. Очень очень долго грузит.
Допустим, пришло обновление core, обновляю, перезагружается НА и всё, долгая загрузка, записи в лог что интеграция грузит больше 10 минут. И интеграция так и не загружается. Доступа нет.
Захожу в перезагрузить хост(типа комп перезагрузить полностью), опять долго грузит, но после этого работает без сбоев. И так до следующего обновления. Проблема примерно уже пол года, вспоминаю конечно только при обновлении в основном или при перезагрузках. Вот решил написать. Интеграцию помню пробовал  переустанавливать с заменой имени хоста ещё с пол года назад

**Comment by AlexxIT** [comment]
После каждого обновления ХА интеграция ставит библиотеку Dataplicity заново из интернета. При слабом интернете/сервере эта установка может занять время.
