### ISSUE TITLE
listening to a different port in the wormhole rather than 80

### ISSUE THREAD

**Issue by anu43** [AlexxIT/Dataplicity#15]
The title speaks for itself but let me ask it anyway. Is there a way to listen to a different port in the wormhole setup rather than the default port 80?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Dataplicity/blob/6205c81a2fbbd36eddd5fc530a46a44acaf8a761/custom_components/dataplicity/__init__.py#L48-L49

**Comment by anu43** [comment]
I couldn't find such directory tree in my setup. Is there a chance that this occurs because I installed the dataplicity via `curl -s https://www.dataplicity.com/251ezhfs.py | sudo python` this command?

**Comment by AlexxIT** [comment]
This project only about Home Assistant component. You need to ask the developers about Dataplicity support.
