### ISSUE TITLE
crashes on app launch

### ISSUE THREAD

**Issue by sergeymatsay** [AlexxIT/Dataplicity#18]
Home Assistant 2023.1.5
Supervisor 2022.12.1
Frontend 20230110.0-latest

The Dataplicity add-on is installed. Worked for over a year with no problems. Since yesterday, when launching an application on android, not from the home network, but at the address https://ххххх-ххххх.dataplicity.io throws out. Sometimes you get this message. see screenshot

![Screenshot_20230117_202921_Home Assistant](https://user-images.githubusercontent.com/95618955/212976442-61a94016-9855-4c04-a056-21605b8e4124.jpg)
Установлено дополнение Dataplicity. Работало больше года без проблемм. Со вчерашнего дня при запуске приложения на android не из домашней сети, а по адрессу https://ххххх-ххххх.dataplicity.io выкидывает. Иногда выскакивае вот такое сообщение.  смотрите скрин

**Comment by redykredyk** [comment]
Тоже самое и у меня...

**Comment by Dreamer0107** [comment]
Да, и у меня такая же проблема

**Comment by AlexxIT** [comment]
I have same problem for my https://xxx.duckdns.org/
Looks like Chrome issue. You need to disable "Safe Browsing" feature if you want to continue using chrome with dyndns-like services.
