### ISSUE TITLE
Home Assistant can no longer connect to backend

### ISSUE THREAD

**Issue by dragonflyuk** [AlexxIT/Dataplicity#19]
I've been using the add-on for a couple of years now, however after a recent update to HA, I can no longer connect to the backend when accessing over dataplicity.

After the Login pages I constantly get messages along the lines of 

`Unable to connect to Home Assistant.

Retrying in 44 seconds...

`

**Comment by Gferretta** [comment]
+1

**Comment by fv71** [comment]
+

**Comment by fv71** [comment]
+1
 disk poll failed unable to contact JSONRPC server 'https://api.dataplicity.com' (<urlopen error [Errno -3] Try again>)

**Comment by dragonflyuk** [comment]
Can I ask why the report is marked as invalid, if nothing else it might give me a clue as to fixing, if it's a problem on the system?

**Comment by luischopy** [comment]
The same thing happened to me, I have not found a solution.

**Comment by AlexxIT** [comment]
Because this is yet another problems with Dataplicity service. And not a problem of this component.
I'm not related to owners of this service and can't do anything with this.
The stability is cost money. But you want the stability for free.

**Comment by dragonflyuk** [comment]
okay thanks, so is it something with Dataplicity that's  changed, and not the HA update that caused this?

**Comment by Jamiro75** [comment]
The strange Is that, there isn't any issue in the dataplicity, and in their
site the status Is ok.
https://status.dataplicity.com/

Il mer 22 feb 2023, 06:42 dragonflyuk ***@***.***> ha scritto:

**Comment by dragonflyuk** [comment]
> +1 disk poll failed unable to contact JSONRPC server 'https://api.dataplicity.com' (<urlopen error [Errno -3] Try again>)

@fv71 where did you find the error, I'm not seeing it in my HA logs?

**Comment by AlexxIT** [comment]
Something like this has happened many times throughout the existence of this integration.
The Dataplicity site never shows these errors.
They go away on their own without any intervention after a few days or weeks.

**Comment by dragonflyuk** [comment]
I haven't seen the errors before, but infairness I problably don't use the Dataplicity connection, a huge amount, but when I need it I tend to be a 100miles away :-(

I think this is different as I am getting authentication errors in HA

`Login attempt or request with invalid authentication from 194.110.13.25 (194.110.13.25). Requested URL: '/auth/token'. (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)`

I assume the 192.110 is a dataplicity IP, so I tried adding that to trusted range, but I still get the same errors.

**Comment by fv71** [comment]
> > +1 disk poll failed unable to contact JSONRPC server 'https://api.dataplicity.com' (<urlopen error [Errno -3] Try again>)
> 
> @fv71 where did you find the error, I'm not seeing it in my HA logs?

It was an error in the HA log, but after the reboot, it was gone, although there is still no access from the outside

**Comment by Gferretta** [comment]
Hi all
It's been almost 1 week now and the remote access error persists.
This time, in my case, the strange thing is that the HA responds to the ping from the outside and the site does not appear as down.
If I log in to the dataplicity app, my HA is green and I can log into my RPi3 with no problem and turn the wormhole on/off.
What's more, the login page appears externally, I enter my HA credentials and after accepting myself, the message "Unable to connect to Home Assistant. Retrying in 44 seconds..." appears.


> The stability is cost money. But you want the stability for free.

Alex
I see that you mention or refer to the use of the free version.
Does this not happen with the paid version?

Thank you
Regards

**Comment by genrihb** [comment]
Same problem for over 2 week

**Comment by nw-cd** [comment]
Аналогичная проблема. Аккаунт платный. После ввода логина и пароля постоянно пишет Unable to connect to Home Assistant. Retrying in 44 seconds...

**Comment by arsenal3008** [comment]
It started 2 weeks ago

**Comment by ViktuK359** [comment]
Тож отмечусь, да как то странно работает, в вэб-морду не пускает, хотя Алиса при этом отлично работает.

**Comment by Alex2zl** [comment]
Аналогичная проблема. Видится проблема в доступе к вебморде
В одной из статей по организации удаленного доступа, там поднимали ssh туннель и ставили nginx, есть фраза 
`Важный момент, интерфейс Home Assistant (который называется lovelace) активно работает через websocket, поэтому нужно не забыть правильно прописать проксирование websocket в nginx. Если это не сделать, то появится страница Home Assistant с ошибкой "Unable to connect to Home Assistant."`
Я в этом не сильно разбираюсь, но, возможно, проблема в websocket?

**Comment by arsenal3008** [comment]
> Аналогичная проблема. Видится проблема в доступе к вебморде В одной из статей по организации удаленного доступа, там поднимали ssh туннель и ставили nginx, есть фраза `Важный момент, интерфейс Home Assistant (который называется lovelace) активно работает через websocket, поэтому нужно не забыть правильно прописать проксирование websocket в nginx. Если это не сделать, то появится страница Home Assistant с ошибкой "Unable to connect to Home Assistant."` Я в этом не сильно разбираюсь, но, возможно, проблема в websocket?
nginx не стоит, стоит самба, ещё пару недель назад все работало

**Comment by Gferretta** [comment]
It is obvious that this problem is more than a matter of access, as it happened many times before and it was unrelated to this integration, an error of the website.
But this time with the wormhole link it is accessed without problems, the ping responds correctly, all the sensors are updated well in remote access, it asks for the HA access credentials, and just after that, the error message appears with the " retry in xxx seconds"
Therefore I also think that there was some change with the lovelace that is causing problems when displaying the screen accessing remotely using Dataplicity.

**Comment by dpbarinov** [comment]
Вчерашний ответ от поддержки Dataplicity

Hey! We are almost sure it is not our fault. Currently, I'm trying to understand home assistant documentation about integration creation (it's hell complicated) to find bug in the custom component. But it will take a time.

**Comment by Fierys** [comment]
+1

**Comment by devbis** [comment]
It looks like nginx on Dataplicity's side incorrectly handles WSS upgrade

```
GET wss://<SUBDOMAIN>.dataplicity.io/api/websocket
[HTTP/1.1 400 Bad Request 1986ms]


HTTP/1.1 400 Bad Request
Date: Mon, 06 Mar 2023 11:52:57 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 32
Connection: keep-alive
Server: nginx/1.23.3
```

And no text response.

**Comment by ffrants** [comment]
Looks like they fixed the issue. Works for me

**Comment by Fierys** [comment]
Yes, it's working now!

**Comment by AlexxIT** [comment]
Well. Looks like problem was not with integration. Because the sources of integration have not changed for two years

**Comment by Psytoshgen** [comment]
yup? looks like trouble no longer exist... after "HA security issue" was fixed?

**Comment by Gferretta** [comment]
> Yup! looks like trouble no longer exist... after "HA security issue" was fixed?

May be?

**Comment by Gferretta** [comment]
> Hey,
> 
> well spotted. It seems we did have a WS Upgrade bug.
> 
> We pushed a fix for that yesterday and we've just been quietly monitoring it since. So far it seems like good news: we ran up a HASS client and have validated that it's now working for our test system, and we've had positive reports from a couple of your community who kindly reached out to us through our support channels. We'll stay glued to this GitHub Issue for a while so please do let us know should you see any residual issues.
> 
> We do try to follow the Custom Component threads fairly closely but should you run into any other issues down the line and we are a little late to the party responding to GitHub Issues for Custom Component, please give us a nudge through our standard support lines and we'll be happy to help out. Thank you again for your patience and understanding, and for taking the time to investigate this issue.
> 
> Grigorij,
> Dataplicity Team

Hi Grigorij

Can you see this New problem?
https://github.com/AlexxIT/Dataplicity/issues/22

Thanks

**Comment by Fierys** [comment]
I join!
After updating to Home Assistant 2023.6, it stopped working.. ((

**Comment by AlexxIT** [comment]
The original problem is no longer relevant.
