### ISSUE TITLE
Нет соединения после обновления HA на 2023.6

### ISSUE THREAD

**Issue by remarkua** [AlexxIT/Dataplicity#22]
Компонент переустанавливал.
На Dataplicity устройство удалял и подключал снова.
Результата нет.
![Screenshot 2023-06-09 083334](https://github.com/AlexxIT/Dataplicity/assets/55970900/c3f98917-6f39-47c3-b8d7-910a718c953a)

**Comment by OlegBON1** [comment]
Та же самая ...

**Comment by TovArtem** [comment]
Тоже перестал работать

**Comment by ananyevgv** [comment]
Тоже перестал работать 2023.6.0 2023.6.1

**Comment by arsenal3008** [comment]
Не работает с утра, вчера еще работало.

**Comment by semen1978** [comment]
не работает после обновления ХА.

**Comment by Gferretta** [comment]
Hi
This New problem that not connect from outside of home, is in AlexxIT Dataplicity integration or in Dataplicity Provider side?
Problem began with version 2023.6.x

It's frustrating.  

Regards

**Comment by dpbarinov** [comment]
Comment from Dataplicity

Ok, thank you for information and notifing me right away after problem happened. I know which bug it is. We need to update dataplicity agent to make dataplicity work with python 3.11. I notified our developers that it is urgent case and they are working on it now. We will try to release new version as fast as possible.
Grigorij
--

Grigorij
Dataplicity

**Comment by Gferretta** [comment]
> Comment from Dataplicity
> 
> ## Ok, thank you for information and notifing me right away after problem happened. I know which bug it is. We need to update dataplicity agent to make dataplicity work with python 3.11. I notified our developers that it is urgent case and they are working on it now. We will try to release new version as fast as possible.
> Grigorij
> Grigorij Dataplicity

Any news?
Not working yet,

**Comment by dpbarinov** [comment]
Hey Dmitry,
I understand you need it to have robust remote access for your Home Assistant, and our engineers doing everything they can to release new agent version as fast as possible. For now I cannot provide any new informations, I will inform you when it will be ready.
Best Regards,
Grigorij

**Comment by axyskus** [comment]
> > Comment from Dataplicity
> > ## Ok, thank you for information and notifing me right away after problem happened. I know which bug it is. We need to update dataplicity agent to make dataplicity work with python 3.11. I notified our developers that it is urgent case and they are working on it now. We will try to release new version as fast as possible.
> > Grigorij
> > Grigorij Dataplicity
> 
> Any news? Not working yet,

Unfortunately not yet

**Comment by AlexxIT** [comment]
#21
