### ISSUE TITLE
After updating to Home Assistant 2023.6 - Dataplicity not working...

### ISSUE THREAD

**Issue by Fierys** [AlexxIT/Dataplicity#23]
After updating to Home Assistant 2023.6 - Dataplicity not working...
When I try to connect I see:

"Device not Connected
Dataplicity is unable to connect to your device. It may be offline".

**Comment by AlexxIT** [comment]
#21

**Comment by Fierys** [comment]
Thank you! After upgrading to v1.1.0 - everything works!
