### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Penumbra168** [AlexxIT/Dataplicity#24]
![00000](https://github.com/AlexxIT/Dataplicity/assets/114436833/02743498-d84b-4ffc-b074-fd85fb992419)

Обновил НА до 
Home Assistant 2023.6.1
Supervisor 2023.06.2
на всякий случай в ручную переустановил Dataplicity заново. 
сервис Dataplicity  машину видит но пишет что НА offline
в логе все время сыпется ошибка : 

> 023-06-15 00:12:12.648 ERROR (m2m) [m2m] error handling websocket event
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 265, in run
>     self.on_event(event)
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 281, in on_event
>     self.on_binary(event.data)
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 327, in on_binary
>     self.on_packet(packet)
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 347, in on_packet
>     self.dispatcher.dispatch(packet_type, packet_body)
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/dispatcher.py", line 80, in dispatch
>     return self.dispatch_packet(packet)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/dispatcher.py", line 92, in dispatch_packet
>     arg_spec = inspect.getargspec(method)
>                ^^^^^^^^^^^^^^^^^^

**Comment by AlexxIT** [comment]
#21
