### ISSUE TITLE
Перестала работать интеграция после обновления НА

### ISSUE THREAD

**Issue by Coldfire2** [AlexxIT/Dataplicity#25]
Здравствуйте!
Удаляю, ставлю 1.2.0 заново, устройство на сайт добавляется, а в НА пишет что "Нет устройств или объектов. Не удалось настроить".
Как победить подскажите плз ?
Спасибо!

**Comment by AlexxIT** [comment]
Issue in this integration should be written in English. The installation error should be in the Home Assistant logs.
