### ISSUE TITLE
Modbus connection with Logo stop working after setting Dataplicity connection

### ISSUE THREAD

**Issue by sandrinoz600** [AlexxIT/Dataplicity#28]
After installing the remote connection from the outside with dataplicity the connection with Siemens Logo via Modbus stopped working.

**Comment by sandrinoz600** [comment]
![Screenshot 2024-05-28 182227](https://github.com/AlexxIT/Dataplicity/assets/36002291/e37697ec-e911-4b50-9e5b-068fe61861f6)

**Comment by AlexxIT** [comment]
I don't think the problems are related
