### ISSUE TITLE
The various Hass menus don't open

### ISSUE THREAD

**Issue by F0min-ivan** [AlexxIT/Dataplicity#4]
Source: components/system_log/__init__.py:190
Повторяется огромное количество раз. Сам сайт работает глючно. Часто не открываются различные меню и тд
Home assistant 2021.7.3

**Comment by F0min-ivan** [comment]
Сейчас приходиться использовать обратный ssh тунель (проброс портов) через vps от амазон,  nginx  с сертификацией от let's encrypt и поддоменом duckdns. Хотя это очень муторный вариант. Хотя все равно интересуюсь данным проектом, так как это самый простой и бесплатный способ получить удаленный доступ к HA серверу с серым ip. На данный момент эту  интеграцию использую как запасной вариант (доступ из консоли работает отлично).

**Comment by AlexxIT** [comment]
This is Dataplicity service bug. Can't be fixed locally
