### ISSUE TITLE
States of Light Bulbs with Tuya v2 integration lose connection and not updated with Dataplicity

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/Dataplicity#6]
Hi
I have noticed that the lights that I have with the Tuya v2 integration lose connectivity and do not update after the first interaction when I log in from Dataplicity.
That is, if the light was off I can turn it on, it shows the change but then the light is inaccessible and I can no longer operate or turn it off.
When exiting and re-entering HA it does the same again, it allows me to control the action only the 1st time and then I have no more access.
Could it be some open / closed ports issue?

**Comment by AlexxIT** [comment]
Duplicate #4 
Dataplicity service bug. Can't be fixed locally
