### ISSUE TITLE
504 Gateway

### ISSUE THREAD

**Issue by wisesokol** [AlexxIT/Dataplicity#7]
Hello. Do not work Dataplicity. When i try to coonect with https://unushered-snowshoe-3154.dataplicity.io/ i get 504 error.

Dataplisity can connect to ssh of HA

core-2021.5.4 
supervisor-2021.06.6

**Comment by x-logger** [comment]
I have same problem.
Core-2021.7.3
Supervisor-2021.06.8
Ssh works well, but wormhole  with 504 err

**Comment by Jamiro75** [comment]
the same for me 504 Gateway Time-out dataplicity v1.0.4
 core 2021.7.3
jamiro75

**Comment by Gferretta** [comment]
> Hello. Do not work Dataplicity. When i try to coonect with https://unushered-snowshoe-3154.dataplicity.io/ i get 504 error.
> 
> Dataplisity can connect to ssh of HA
> 
> core-2021.5.4 
> supervisor-2021.06.6

![SmartSelect_20210719-192602_Chrome.jpg](https://user-images.githubusercontent.com/65413059/126235264-00e6b3d5-e7c5-4dba-bd0d-ca0bd64b5042.jpg)

**Comment by wisesokol** [comment]
Today is work! Maybe dataplicity worked wrong

**Comment by AlexxIT** [comment]
Temporary problems with Dataplicity service

**Comment by anu43** [comment]
Having the same problem in my https://occultism-eel-5449.dataplicity.io account. Problems seems to continue more than 1 day. Is it normal?

**Comment by Gferretta** [comment]
Yesterday and today I have the same error, yet not resolved.

Anybody more?

**Comment by AlexxIT** [comment]
Yes. All users has problems

**Comment by Gferretta** [comment]
> Yes. All users has problems

thanks for answer

**Comment by anu43** [comment]
> Yes. All users has problems

Do you have any idea when it would be resolved?

**Comment by Jamiro75** [comment]
But Is problem from dataplicity or this  integration- ha ?
Thanks
Simone

**Comment by AlexxIT** [comment]
This not first time than service fail. It happens few times in year.
You can switch to another service. As example NabuCasa.

**Comment by Jamiro75** [comment]
Yes of course may be happen, i've also a backup with remote.it Now the service is come back, and it's ok.
many thanks

**Comment by anu43** [comment]
> Now the service is come back, and it's ok.

same here. thanks!

**Comment by Gferretta** [comment]
All Day with same problem.
Anybody more?

**Comment by JessmenTh** [comment]
jep problem startet ca. 21:30 Berlin.
update, upgrate, register new device, nothing changed ... for ~10min the Wormhole Link worked but no Sub Dir was available. ATM all requests run into "504 Gateway Time-Out" .

**Comment by JessmenTh** [comment]
> jep problem startet ca. 21:30 Berlin. update, upgrate, register new device, nothing changed ... for ~10min the Wormhole Link worked but no Sub Dir was available. ATM all requests run into "504 Gateway Time-Out" .

No its working for me again (ca. 06:30 Berlin) ... Thx

**Comment by Gferretta** [comment]
Another Day with same problem!

**Comment by JessmenTh** [comment]
yes

**Comment by JessmenTh** [comment]
> > Hello. Do not work Dataplicity. When i try to coonect with https://unushered-snowshoe-3154.dataplicity.io/ i get 504 error.
> > Dataplisity can connect to ssh of HA
> > core-2021.5.4
> > supervisor-2021.06.6
> 
> ![SmartSelect_20210719-192602_Chrome.jpg](https://user-images.githubusercontent.com/65413059/126235264-00e6b3d5-e7c5-4dba-bd0d-ca0bd64b5042.jpg)

(2022-02-08 15:30) Problem reappeared

**Comment by Smandurlo** [comment]
You probably want to remove your HA remote link in pubblic 🤦
