### ISSUE TITLE
[agent] unable to associate m2m identity

### ISSUE THREAD

**Issue by meliborn** [AlexxIT/Dataplicity#8]
Today I started to receive this kind of errors:

`2021-12-11 16:10:54 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. put m2m/devices/5905db75-746c-4f05-8eb0-208e2ddb0aee/ <Response [500]>")`

```
Logger: agent
Source: /srv/homeassistant/lib/python3.8/site-packages/dataplicity/client.py:308 
First occurred: 11 декабря 2021 г., 16:10:46 (13 occurrences) 
Last logged: 11 декабря 2021 г., 16:12:00

unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. put m2m/devices/5905db75-746c-4f05-8eb0-208e2ddb0aee/ <Response [500]>")
```

**Comment by AlexxIT** [comment]
Some problems with dataplicity severs. Can't do anything

**Comment by meliborn** [comment]
@AlexxIT are you sure? I don't see any incidents here https://status.dataplicity.com, but can't connect to my HA

**Comment by AlexxIT** [comment]
Yes. I have the same error.
